export enum EPages {
  LOGIN = "LOGIN",
  COMPANY = "COMPANY",
  ORDERS = "ORDERS",
  TABLES = "TABLES",
  CATEGORIES = "CATEGORIES",
  KITCHEN = "KITCHEN",
  POSITIONS = "POSITIONS",
  USERS = "USERS",
  BILLING = "BILLING",
  DAY_STATS = "DAY_STATS",
  PERIOD = "PERIOD",
}
