export enum ETableTypes {
  TABLE_SQUARE = "table_s",
  TABLE_CIRCLE = "table_c",
  WALL = "wall",
  FLOWER = "flower",
  DOOR = "door",
  WINDOW = "window",
  KITCHEN = "kitchen",
  GRASS = "grass",
  PAVILION = "pavilion",
  CHAIR = "chair",
  INFO = "info",
  TRASH = "trash",
  WC = "wc",
  BAR = "bar",
  PLAY = "play",
  MUSIC = "music",
  TREE = "tree",
  LIGHT = "light",
  STORAGE = "storage",
}
